on: [push]
jobs:
  pdfs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kovirobi/robs-cs-typst:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          export TYPST_ROOT="$PWD"
          mkdir out
          typst compile ./ocaml-prep.typ ./out/ocaml-prep.pdf
          for typ in ./1-functional-programming/*.typ; do
            typst compile "$typ" "./out/$(basename -s.typ "$typ").pdf"
            polylux2pdfpc "$typ"
            mv "${typ%.typ}.pdfpc" ./out
          done
      - uses: actions/upload-artifact@v4
        with:
          name: robs-cs-${{ github.sha }}
          path: out/
